version: '3'
services:
  nginx:
    image: 'nginx:stable'
    ports:
      - '8888:80'
    volumes:
      - ./:/var/www/memo
      - ./docker_configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Sync config from host
    networks:
      - kpm
networks:
  kpm:
    driver: bridge
